### ISSUE TITLE
CI: Installing pip for Python 3.5 job broken

### ISSUE THREAD

**Issue by salkinium** [modm-io/lbuild#59]
```
Successfully installed dpl-pypi-1.10.16
2161 gem installed
2172021-02-18 17:27:46 URL:https://bootstrap.pypa.io/get-pip.py [1929903/1929903] -> "-" [1]
218Traceback (most recent call last):
219  File "<stdin>", line 24244, in <module>
220  File "<stdin>", line 199, in main
221  File "<stdin>", line 82, in bootstrap
222  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
223  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
224  File "<frozen importlib._bootstrap>", line 896, in _find_spec
225  File "<frozen importlib._bootstrap_external>", line 1171, in find_spec
226  File "<frozen importlib._bootstrap_external>", line 1147, in _get_spec
227  File "<frozen importlib._bootstrap_external>", line 1128, in _legacy_get_spec
228  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
229  File "<frozen importlib._bootstrap_external>", line 565, in spec_from_file_location
230  File "/tmp/tmpacrexxzg/pip.zip/pip/_internal/cli/main.py", line 60
231    sys.stderr.write(f"ERROR: {exc}")
232                                   ^
233SyntaxError: invalid syntax
234Couldn't install pip, setuptools, twine or wheel.
```

Seems to be related to this: https://stackoverflow.com/questions/65896334/python-pip-broken-wiith-sys-stderr-writeferror-exc

**Comment by salkinium** [comment]
Also Travis-CI.org is deprecated now, so the job doesn't run at all. We need to move to GitHub Actions.

**Comment by salkinium** [comment]
This was done some time ago.
